### PR TITLE
Added CHESS in games list

### PR DESCRIPTION
**Pull request by code-note**
**https://www.chess.com/**

**Common web-app to play chess. Learn to play chess online else play with over 15 million users around the globe or against AI with various difficulty levels.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x] The app I added is not a duplicate.

### CODE REVIEW

**Comment by aviaryan** [comment]
@code-note It looks like that website requires creating account to use it. I am sure there are no-login alternatives available also.

**Comment by code-note** [comment]
Hey @aviaryan thanks for your review ! I see that it requires account only for playing other players online, but not for playing AI or learning tactics, so basically we can use the app but it needs acc only for  storing progress and stuff and not for its basic feature, as mentioned in the list README, you still want me to look for alternative ?

**Comment by aviaryan** [comment]
@code-note Yes, I guess. There are sites which allow multiplayer without creating an account. One such example is https://www.sparkchess.com/

**Comment by code-note** [comment]
@aviaryan sorry for the inconvenience, I've switched to sparkchess, though it has no interactive chess learning guide unlike chess.com but as we are mainly focused on playing with a no-login alternative, sparkchess is more useful. 
Thanks  for the guide.

**Comment by aviaryan** [comment]
@code-note Thanks for your contribution. Merging this now.

**Pull request merged**
