### PR TITLE
Add Youtube Dynamic Playlists

### PR DESCRIPTION
**Pull request by ndom91**
**[youtube.ndo.dev](https://youtube.ndo.dev)**

**Disclaimer: this app is a sideproject of mine**
However, it is a web app that does not require an account, and does what it says on the tin. 

The user can either drag and drop youtube urls onto the page, or it will recognize youtube URLs in the clipboard, and create dynamic playlists. That way you dont have to junk up your youtube account with all sorts of throw-away playlists.

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x] The app I added is not a duplicate.

### CODE REVIEW

**Review by hn-agnihotri29 — CHANGES_REQUESTED** [review]
I had trouble dragging the video's link, can you make a video showing a step-by-step method of how the site works?

**Comment by ndom91** [comment]
> I had trouble dragging the video's link, can you make a video showing a step-by-step method of how the site works? 

Yeah so there's a gif in the README at https:/github.com/ndom91/youtube-playlists. 

Did that not work for you?

**Review by hn-agnihotri29 — APPROVED** [review]
Thanks for contributing, Your web app is exciting, it has a way to play different videos of a choice, hope it has much more features in the future.

**Review by hn-agnihotri29 — CHANGES_REQUESTED** [review]
Sorry for the late reply. Please resolve the merge conflict in your PR, so I am able to merge your PR.

**Comment by ndom91** [comment]
Ah damn it, this was from 3 years ago. The source repo doesn't exist anymore. I've tried to make changes in Github directly, etc. unfortunately it doesn't allow me.

image

Any way you can make changes still? If not i'll just open a new PR, but I'd like to get this 3 year old one in just for the sake of it :sweat_smile:

**Review by hn-agnihotri29 — COMMENTED** [review]
Please, create a new PR so that there is no conflict.

**Comment by ndom91** [comment]
Damn, wish we could have made it work with this 3 year old PR :joy:

Anyway, here's the new one: https://github.com/aviaryan/awesome-no-login-web-apps/pull/293

**Pull request closed without merging**
