### PR TITLE
Add TypingWeb

### LINKED ISSUE #80: typingweb.com query
Should we include typingweb.com into the list ?
This web-app takes us through a course to master touch typing, encourages users to practice by providing them with badges and other stuff. We are short of such web-apps too.
Need Account to track progress and accumulate badges.
Let me know if we need this in the list @aviaryan .

### PR DESCRIPTION
**Pull request by Anshuman-Verma**
**https://www.typing.com/student/start**

Fixes #80 
**Master touch-typing at ease. Go through the predefined typing courses and accumulate badges and track progress by creating an account.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x] The app I added is not a duplicate.

### CODE REVIEW

**Comment by Anshuman-Verma** [comment]
Finally a clean merge.  :open_mouth:

**Comment by Monal5031** [comment]
@Anshuman-Verma practise makes man perfect 😛

**Comment by aviaryan** [comment]
@Monal5031 ROFL . You have grown a lot @Anshuman-Verma :-P

**Comment by Monal5031** [comment]
@aviaryan anyone learning from you would 😝

**Comment by Anshuman-Verma** [comment]
@aviaryan all thanks to you :smile:

**Comment by aviaryan** [comment]
@Anshuman-Verma Also I was trying to use a Naruto reference there. 
Try `cat naruto_eng_subs_all.txt | grep -i "grown a lot"` and you will see.

**Comment by Anshuman-Verma** [comment]
@aviaryan is as awesome as ever ! :raised_hands:

**Comment by Monal5031** [comment]
@Anshuman-Verma let's compile a list of Awesome people and add @aviarayn on top of it  😝

**Pull request merged**
