### PR TITLE
added new entry to audio and video section

### PR DESCRIPTION
**Pull request by arpit1997**
If you are adding something, explain briefly why do you think that web app is **awesome**.

If you are changing something, explain briefly why that change was needed.

Apart from that, go through the following checkpoints --

- [ ] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable 
for this project. 
- [ ] I have edited the PR title from "update README.md" to something meaningful.

Vdeotoolbox is a free video editor with easy to use interface and good features.

### CODE REVIEW

**Comment by aviaryan** [comment]
@arpit1997 Please follow the pull request template and update this pull request.

**Comment by aviaryan** [comment]
@arpit1997 Thanks. Video Toolbox looks impressive with a good set of features.

**Comment by vermanil** [comment]
It's good. But, Account is mandatory.

**Comment by aviaryan** [comment]
@vermanil So it has been tagged with an `[Account]` tag.

**Pull request merged**
