### PR TITLE
added new entry to Programming Editors and IDEs section

### PR DESCRIPTION
**Pull request by arpit1997**

### CODE REVIEW

**Comment by aviaryan** [comment]
Please check the PR title and update it so that it is more meaningful.

**Comment by aviaryan** [comment]
This PR is removing is.gd . I don't think that is intentional.

**Comment by arpit1997** [comment]
Oh.. my bad. I may have removed it by mistake. Close this PR I will send another one or you can do the changes and then merge it.

**Comment by m1guelpf** [comment]
@arpit1997 You can change things in the Files Changed tab of this PR

**Pull request closed without merging**
