### PR TITLE
Add codepad to Programming Editors and IDEs

### PR DESCRIPTION
**Pull request by chankeypathak**
**http://codepad.org/**

**An online IDE which is similar to Ideone but is older than that**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x] The app I added is not a duplicate.

### CODE REVIEW

**Comment by aviaryan** [comment]
@chankeypathak Thanks for your contribution. 
codepad might be old but it still doesn't support giving inputs to the program. This makes it inferior with respect to 2-3 online IDEs already in this list. Also we won't like to add too many similar tools in this list (2 is ideal, 3 is fine). Keeping this in mind, I don't think codepad is suitable for the list. 
What do you say?

**Comment by chankeypathak** [comment]
@aviaryan The main feature of codepad, missing from other online IDEs is that you can create a project page. See http://codepad.org/mkproj for details.

**Comment by chankeypathak** [comment]
Besides, your list is also missing below:

 - http://www.koding.com/
 - https://c9.io/

Let me know if you want them to be included.

**Comment by aviaryan** [comment]
@chankeypathak In that case, please mention the main features + limitations in the app description. Right now, the description is very generic.

**Comment by chankeypathak** [comment]
Why did the build fail? Are parenthesis not allowed?

**Comment by aviaryan** [comment]
@chankeypathak Build fail is not related to your commit.
Btw, please add that limitation too i.e. no support for reading from stdin.

**Pull request merged**
