### PR TITLE
Add Resume Nation

### PR DESCRIPTION
**Pull request by amitmerchant1990**
**https://resume-nation.github.io**

**This is an open source resume builder progressive web app. It fulfils the purpose of this list i.e it works without any sort of registration. In fact, it can be used as a standalone app offline as well.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x] The app I added is not a duplicate.

### CODE REVIEW

**Comment by aviaryan** [comment]
Wow. This looks good.

**Comment by aviaryan** [comment]
Can you please add more description to it? like can it export to PDF, if yes please add it. Also add that it works offline and support some themes.

**Comment by amitmerchant1990** [comment]
Sure. I'll add necessary info which you've listed above.

**Comment by amitmerchant1990** [comment]
Added more info as we discusses. Please check the same and let me know if you need any more addition.

**Comment by aviaryan** [comment]
Thanks for this PR, @amitmerchant1990

**Pull request merged**
