### PR TITLE
add StackEdit.io, Daily Todo, Polls.io

### PR DESCRIPTION
**Pull request by danivijay**
**https://stackedit.io/**

**Rich in-browser markdown editor that works offline.**

**https://dailytodo.org/**

**Simple todo list maker.**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x] I have read the [Contribution guidelines](https://github.com/aviaryan/awesome-no-login-web-apps/blob/master/CONTRIBUTING.md) and I am confident that my PR is suitable. 
- [x] This pull request has a descriptive title. For example, `Add [App name]`, not `Update readme.md` or `Added new entries`.
- [x] The app I added is not a duplicate.

### CODE REVIEW

**Comment by aviaryan** [comment]
@danivijay Can you confirm if polls.io is working? Others look good. 😄

**Comment by danivijay** [comment]
Oops! My bad. Was working previously. Removed it.

**Comment by danivijay** [comment]
Can you have a look at this now @aviaryan ? I've removed polls.io

**Comment by aviaryan** [comment]
Thanks @danivijay 😄

**Pull request merged**
